---
title: 'Lab Assignment #3: Wrapping the world in a package'
author: "Heike Hofmann"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE, echo = TRUE)
```
# Outline

- Creating an R package

- Cleaning up last lab's code and wrapping it in functions

- Writing some tests and documentation


<br><br><br>

The final deliverable is a link to your team's github repository containing a functional R package that passes checking without any errors, warnings or notes. 

For the purpose of grading, I will install the package, make sure that it passes checking, and try to break your code with a couple of tests :)


---

# Lab organization

1. Follow the Github Classroom invite and join the team you are assigned to in Canvas (one of Team 1 through 8)

2. Accepting the invite gives you access to a Github repository that was created using `usethis` functionality `create_package` and `use_readme_rmd`. 

3. A function `thin(x, tolerance = 0.1, minarea = 0.01)` is included in file `thin.r` in the `R` folder. Additionally, the folder `lab2-scripts` contains scripts `team-1.r`, ..., `team-6.r` with solutions from the last lab.

4. This repository is supposed to provide the basis for your R package.


---

# Last time ...

... you were asked to write a function that allowed you to create a data frame from 
a `geometry` variable

# This time:

- each team member is asked to pick the solution to last time's lab (available from the `lab2-scripts` folder) from a different team (and not the team they were on)

- wrap the solution into a function of the form

`team_X <- function(file, tolerance)` where `X` is the solution for team X used,  file is a file path to a shape file and 
tolerance is the value used for thinning the polygon


The return value is a data frame of the geographic information of the polygons and the additional information (such as name of the country, name of the territory/state, ...)

---

# Data

Include one example dataset in your package (pick one country and get everything into the right shape).

Dont forget to document the function.

# Documentation

Using roxygen tags, appropriately document function `team_X`. (Don't forget about the `thin` function)

Include at least one example for every function of the package.

# Assertions

Make sure to include checks at the start of your function to make it as unbreakable as you can and have it working as intended in as many situations as you can think of.

---

# README.Rmd

Your README file is supposed to give an overview of the functionality of your package, i.e. it should include installation instructions and an example for each function. 

# Checks

The function `devtools::check()` runs all of the tests required by CRAN maintainer. 
Your package is supposed to pass these checks without any errors, warnings or notes.

Make sure to browse the web for answers in case of problems and don't forget about our Q&A discussion board! Extra points and candy are on the line!

# Everybody participates!

Remember that github keeps track of who submits what - I expect that every team member contributes to the lab. 
